// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6HMqSvkne6qD3o5XVwMO8UIg6hV4zymU',
    appId: '1:1033761519799:android:b751924e90425a87d4f532',
    messagingSenderId: '1033761519799',
    projectId: 'kmassagechatapp',
    storageBucket: 'kmassagechatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEcNSm_PdLPcYVv9vN_kuQvo9YfYfGuDM',
    appId: '1:1033761519799:ios:6a6f018a47c10d69d4f532',
    messagingSenderId: '1033761519799',
    projectId: 'kmassagechatapp',
    storageBucket: 'kmassagechatapp.appspot.com',
    androidClientId: '1033761519799-nijkguj1jsga82pet5f8gjfls73ahdld.apps.googleusercontent.com',
    iosClientId: '1033761519799-734vurpndadm44chks8v2anl8v7pvel8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapp',
  );
}
